version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: air-admin
      POSTGRES_PASSWORD: air-admin-password
      POSTGRES_DB: air-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
