services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: air-admin-password
      POSTGRES_DB: air_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    env_file: .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    environment:
      NODE_ENV: production
    expose:
      - 3000
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:1.28
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
