version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: air-admin
      POSTGRES_PASSWORD: air-admin-password
      POSTGRES_DB: air-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    container_name: showcase-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://air-admin:air-admin-password@db:5432/air-db
    command: node dist/main

volumes:
  postgres_data:
