version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: air-admin
      POSTGRES_PASSWORD: air-admin-password
      POSTGRES_DB: air-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    env_file: .env
    build:
      context: .
      args:
        PRISMA_BINARY_TARGETS: '["native"]'
    container_name: showcase-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://air-admin:air-admin-password@db:5432/air-db
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    command: sh -c "npx prisma migrate deploy && node dist/main"

volumes:
  postgres_data:
