services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: air-admin
      POSTGRES_PASSWORD: air-admin-password
      POSTGRES_DB: air-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    env_file: .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://air-admin:air-admin-password@db:5432/air-db
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
    expose:
      - 3000
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:1.28
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
